"""prevent duplicate job matches

Revision ID: 2dd854bedbe3
Revises: 85577bd5a9b1
Create Date: 2026-08-20 22:38:30.766308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd854bedbe3'
down_revision: Union[str, Sequence[str], None] = '85577bd5a9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_candidate_match', 'job_matches', ['job_id', 'candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_candidate_match', 'job_matches', type_='unique')
    # ### end Alembic commands ###
